package-lock.json, package.json, src/events/index.ts, src/events/messageCreate.ts, src/events/ready.ts
* New scripts to run `ollama serve` concurrently with the bot client
* `axios` and `concurrently` libraries
* `messageCreate` event registers as a Bot event
=> ollama responds to discord msgs

README.md, src/client.ts, src/events/messageCreate.ts, src/keys.ts, src/utils/events.ts, src/utils/index.ts, src/utils/messageEmbed.ts, src/utils/messageNormal.ts
* Bot can be mentioned to chat now! (this will be a requirement until we added user preferences)
* Tokens can be passes through events now for other listeners
* Previously had to change hardcoded values throughout files, now the `.env` file can be modified to reduce this task
=> Removed Hardcoded vals and Added mentions

.github/CONTRIBUTING.md, .github/style.md, src/client.ts, src/keys.ts, src/utils/env.ts, src/utils/messageEmbed.ts, src/utils/messageNormal.ts, src/utils/streamParse.ts
* Contributing file to know how to set up the environment and develop the bot yourself
* Style guide for developing the bot
* Changed some quotes and removed unnecessary semicolons to follow style
=> Formatting and Contributing

README.md
* Instructions to setup docker and run the images for the application
=> Docker Setup Instructions

.gitignore, package.json, src/client.ts, src/utils/events.ts, src/utils/messageEmbed.ts, src/utils/messageNormal.ts, src/utils/streamParse.ts
* Some comments in `utils/events.ts` to clarify what some of the functions/types were
* The `UserMessage` type
* The json token parser will likely not be used (probably ever) because of the rates that Discord has. Can still be added as a user preference and will add a warning for "delayed" responses
=> Small Documentation and Refactoring

.env.sample, .github/workflows/build-test.yml, docker-compose.yml, package-lock.json, package.json, src/commands/disable.ts, src/commands/index.ts, src/commands/shutoff.ts, src/events/messageCreate.ts, src/keys.ts, src/utils/jsonHandler.ts
* Forgot to add the new environment variable to the docker-compose and workflow, hence the failures
=> Workflows Fix

LICENSE, README.md
* `LICENSE` file to show on repo
* Changed `LICENSE` to be `CC BY 4.0` it's a bit laxer.
=> Change of License

src/events/messageCreate.ts, src/utils/jsonHandler.ts
* Change the `if` dequeue to be a `while` dequeue so it can clean itself up when the capacity changes to be less.
* The Capacity command was not working as intended due to a name changing issue. That is now resolved and the command works!
=> Fix Capacity Command

.github/workflows/build.yml, tests/commands.test.ts, tests/events.test.ts
* Tests did not include new files created for commands and events from #62
* Instead of running the tests on master, it will run on PR
=> CI Fixes and PR Tests

.github/workflows/test.yml
* Added some paths to ignore/run for the Unit Test workflow
* This is not a fix for version incrementing sadly. It might be worth it to just keep it as is because we do not want to ignore:
* `package.json`
* `Dockerfile`
* `docker-compose.yml`
* Unit Tests should be allowed to run against the codebase with new/deprecating dependencies.
=> Test Workflow PR Push Rules

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
* Added issue templates for Feature Requests and Bugs
* Added a PR template
=> Issue and Pull Request Templates

src/commands/capacity.ts, src/commands/messageStream.ts, src/commands/messageStyle.ts
* Modified `interaction.client.user.username` to `interaction.user.username` in certain command files.
* Concurrency was tested with this bugfix and the Ollama update seems to work out of the box for use!
* Please refer to #53 for screenshots.
=> User Preferences Fix

.github/pull_request_template.md, README.md, docker-compose.yml, package-lock.json, package.json
* Adding reminder on Pull Request template to increment version when necessary
* Increment version
=> PR Template Update

.github/workflows/build.yml, .github/workflows/test.yml, package-lock.json, package.json
* Upgraded `ollama-js` dependency to latest.
* Upgraded other development dependencies.
* Fixed issue with tests not running at root level for PRs.
* This runs fine locally with `npm run client`
=> Dependency Upgrade

docker-compose.yml, package-lock.json, package.json, src/commands/capacity.ts, src/commands/channelToggle.ts, src/commands/messageStream.ts, src/commands/messageStyle.ts
* Added `ChannelType.PrivateThread` within the scope of a few commands:
* `modify-capacity`
* `channel-toggle` - Slash Command is likely to be removed in #90 but added it here for now due to criteria
* `message-stream`
* `message-style`
=> Adjusted Slash Command Scope

.github/workflows/build.yml
* Run `build.yml` when a Pull Request is merged into master
=> Run Build Pipelines

.github/workflows/build.yml
* The container build test had the wrong image name. Now the test should reflect the new image name for the app `kevinthedang/discord-ollama` 
* Build issue from #97
=> Fixed Incorrect Image Name

.env.sample, src/keys.ts
* Removed `GUILD_ID` as a necessary environment variable in the `.env.sample` and `src/keys.ts`
=> Removed GUILD_ID as an Environment Variable

docker-compose.yml, package-lock.json, package.json, src/utils/handlers/configHandler.ts
* The `data/` directory is now created if it does not exist on chat to create necessary server/user preferences.
=> Data Directory on Chat for Preferences

.github/workflows/release.yml, README.md
* Added a `Deploy` shield to `README.md` to show the deployment status.
=> Deploy Shield

tests/commands.test.ts
* more extensive pseudocode for testing commands has been written
=> Combine Tech Debt Branches

.github/CONTRIBUTING.md, .github/workflows/coverage.yml, README.md, src/client.ts, src/commands/capacity.ts, src/commands/cleanUserChannelHistory.ts, src/commands/disable.ts, src/commands/messageStream.ts, src/commands/messageStyle.ts, src/commands/threadCreate.ts, src/commands/threadPrivateCreate.ts, src/events/messageCreate.ts, src/events/ready.ts, src/keys.ts, src/utils/configInterfaces.ts, src/utils/env.ts, src/utils/events.ts, src/utils/index.ts, src/utils/mentionClean.ts, tests/commands.test.ts, tests/events.test.ts, tests/getEnvVar.test.ts, tests/mentionClean.test.ts, tests/queue.test.ts, vitest.config.ts
* Updated imports to follow current module structures
* Removed references to dependencies that were removed
* Merged pseudo-code for testing commands, updated test suit names
* Code Coverage support and badge
=> Code Coverage and Clean References

docker-compose.yml, package-lock.json, package.json, src/utils/env.ts
* Validation is carried out by seeing if the variable exists. If not, application will shut down.
* Added IPv4 Address validation. 
* Currently, it only will run against `OLLAMA_IP` because `SUBNET_ADDRESS` and `DISCORD_IP` is not used in the application.
* Added `CLIENT_TOKEN` validation for the generated 72 length tokens from the Discord developer platform.
=> Environment Variable Validation

.env.sample, .github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/test.yml, docker-compose.yml, docs/setup-discord-app.md, docs/setup-local.md, package-lock.json, package.json, src/events/messageCreate.ts, src/keys.ts, src/utils/events.ts, src/utils/mentionClean.ts, tests/mentionClean.test.ts
* Removed instances of `CLIENT_UID` from the application. It seems like it runs fine without it!
* Updated `mentionClean.test.ts` to utilize a static token as it only needs to remove the token.
* Documentation was updated to not mention that the `CLIENT_UID` is needed.
* `CLIENT_UID` was removed from `.env.sample`.
* `CLIENT_UID` was removed from workflows.
=> Remove CLIENT_UID Environment Variable

.env.sample, .github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/test.yml, README.md, docker-compose.yml, docs/setup-docker.md, docs/setup-local.md, package-lock.json, package.json, src/client.ts, src/commands/index.ts, src/commands/pullModel.ts, src/commands/switchModel.ts, src/events/messageCreate.ts, src/keys.ts, src/utils/configInterfaces.ts, src/utils/events.ts, src/utils/messageEmbed.ts, src/utils/messageNormal.ts, tests/commands.test.ts
* Added the `switch-model` slash command. This command can pull models if they do not exist as a backup.
* Removed `MODEL` as an environment variable.
* Models with different parameters like `deepseek-coder:1.3b` can work now. `deepseek-coder` would also be valid since it would just pull/use the latest version of it.
* Removed the `Tokens` type as it is no longer necessary.
* Added fallback environment values for `OLLAMA_IP` and `OLLAMA_PORT` cause why not.
* Documentation was updated as necessary to not include model environment information.
* npm packages were updated to latest for dependencies to reduce vulnerabilities.
* Looks like the latest `discord.js` lost the `.send()` method by adding a type of Channel. Will have to test it out eventually for compatibility.
=> Switch Model Command

.github/CONTRIBUTING.md, README.md, docs/commands-guide.md, docs/events-guide.md
* Removed first, second, and third POV from feature set guide.
* Added a guide sheet for events triggered by this app.
* Modified the name and order of the documentation section in the main README.
=> Feature Set Documentation

README.md, docs/commands-guide.md, docs/events-guide.md
* updates to goals in the base README
* bug fixes to markdown in user guides
=> Updated Guides and Goals 

docker-compose.yml, package-lock.json, package.json, src/utils/messageEmbed.ts, src/utils/messageNormal.ts
* discord.js [v14.16.2](https://github.com/discordjs/discord.js/releases/tag/14.16.2) added a type-guard for text-based channels to check if messages can be sent: [#10482](https://github.com/discordjs/discord.js/pull/10482)
* updated @types/node, @vitest/coverage-v8, vitest, and tsx with their latest respective versions
=> Roll NPM Dependencies Forward

docker-compose.yml, package-lock.json, package.json, src/commands/capacity.ts, src/commands/cleanUserChannelHistory.ts, src/commands/disable.ts, src/commands/messageStream.ts, src/commands/messageStyle.ts, src/commands/pullModel.ts, src/commands/shutoff.ts, src/commands/switchModel.ts, src/commands/threadCreate.ts, src/commands/threadPrivateCreate.ts, src/utils/configInterfaces.ts, src/utils/handlers/chatHistoryHandler.ts
* Instead of Array checks, we define them once and call them `AdminCommand` or `UserCommand`
* Looks like there is no issue right now running locally (also works with containers!). Logic seems to work as intended.
=> Pull/Switch Model Commands Fix

CODEOWNERS
* Added a `CODEOWNERS` file for file/directory ownership
=> Code Owners File

.env.sample, docker-compose.yml, package-lock.json, package.json, src/events/messageCreate.ts, src/utils/handlers/bufferHandler.ts
* Users are now allowed to use `.txt` files in the prompt. This allows for very long messages.
* The input can include extra words besides the text file.
=> Text Files As Prompts

README.md
* No longer doing Docker release so now we need a deploy shield
=> Deploy Badge

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/deploy.yml, .github/workflows/test.yml, docker-compose.yml, package-lock.json, package.json
* Added `MODEL` as an environment variable for running with docker.
=> Fix: missing model env for docker

README.md
* Updated feature goal lists for new issues that were created a while ago
=> Update Documentation with New Features

src/client.ts, src/events/messageCreate.ts, src/utils/events.ts, src/utils/handlers/chatHistoryHandler.ts
* Allows the bot to store messages in a separate channel that is only from users
* Slight code moving that does not change functionality of the application
=> Additional Channel Context Awareness
